[application]

name = "test-webworker"
out_dir = "../target/dist"
asset_dir = "public"

[web.app]

# HTML title tag content
title = "test-webworker"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "org.omusubi.aki.nt.test_webworker"
publisher = "aki.akaguma"

icon = [
  # "icons/icon.ico"
  "assets/app.png",
  "assets/favicon.ico"
]

copyright = "Copyright 2026 aki.akaguma"
category = "Utility"
short_description = "Sample of web worker for multi-threading"
long_description = "Sample of web worker for multi-threading"
