
all: list

MAKEFILE_LIST = Makefile
# Self-documenting Makefile targets script from Stack Overflow
# Targets with comments on the same line will be listed.
list:
	@LC_ALL=C $(MAKE) -pRrq -f $(firstword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/(^|\n)# Files(\n|$$)/,/(^|\n)# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | grep -E -v -e '^[^[:alnum:]]' -e '^$@$$'

.PHONY: list

clean:
	cargo clean

apply-patch:
	cargo patch-crate

android-versionCode:
	cat resources/android/versionCode

android-versionCode-inc:
	vc=$$(cat resources/android/versionCode);vc=$$(($$vc + 1));echo $$vc > resources/android/versionCode
	cat resources/android/versionCode

bundle-web:
	dx bundle --web --release --base-path "/test-webworker"

bundle-desktop:
	dx bundle --desktop --release --package-types appimage

#	dx bundle --desktop --release --features backend_next

bundle-android-aarch64:
	@rm -fr "../target/dx"
	dx bundle --android --release --target=aarch64-linux-android
	./scripts/apk-icon-assemble-r.sh test-webworker aarch64 resources/android

bundle-android-x86_64:
	@rm -fr "../target/dx"
	dx bundle --android --release --target=x86_64-linux-android
	./scripts/apk-icon-assemble-r.sh test-webworker x86_64 resources/android

bundle-android-wva:
	@rm -fr "../target/dx"
	./scripts/wva-apk-icon-assemble-r.sh test-webworker massfib/resources/android massfib/scripts/android-webview-assets-params.toml
