# This is a template parameter used by guic (guidon cli).
[variables]
project_name = "test-webworker"
app_name = "TestWebworkerWva"
package_id = "org.omusubi.aki.wva.test_webworker"
version_code = "1"
version_name = "0.1"
load_url = "https://aki.omusubi.org/test-webworker/"
#
compile_sdk_version = "36"
target_sdk_version = "36"
min_sdk_version = "28"
